### ISSUE TITLE
Uncaught TypeError: Cannot set property 'opacity' of undefined

### ISSUE THREAD

**Issue by beenorgone** [camel-chased/clean2#12]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.5.3
**System**: Ubuntu 14.04.4
**Thrown From**: [Clean2](https://github.com/camel-chased/clean2) package, v0.16.0
### Stack Trace

Uncaught TypeError: Cannot set property 'opacity' of undefined

```
At /home/beenorgone/.atom/packages/Clean2/lib/clean.coffee:59

TypeError: Cannot set property 'opacity' of undefined
    at Object.module.exports.restoreOpacity (/home/beenorgone/.atom/packages/Clean2/lib/clean.coffee:59:22)
    at Object.module.exports.applyConfig (/home/beenorgone/.atom/packages/Clean2/lib/clean.coffee:84:10)
    at Object.module.exports.toggle (/home/beenorgone/.atom/packages/Clean2/lib/clean.coffee:99:6)
    at atom-workspace.subs.add.atom.commands.add.clean2:toggle (/home/beenorgone/.atom/packages/Clean2/lib/clean.coffee:90:28)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/opt/atom/resources/app.asar/src/command-registry.js:260:29)
    at /opt/atom/resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/opt/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:544:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/opt/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:363:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeydown (/opt/atom/resources/app.asar/src/window-event-handler.js:97:36)
    at HTMLDocument.<anonymous> (/opt/atom/resources/app.asar/src/window-event-handler.js:3:61)
```
### Commands

```
     -1:30.8.0 markdown-writer:insert-new-line (atom-text-editor.editor.is-focused)
     -1:30.8.0 markdown-lists:insert-new-line (atom-text-editor.editor.is-focused)
     -1:30.1.0 editor:move-to-end-of-screen-line (atom-text-editor.editor.is-focused)
     -1:29.3.0 editor:move-to-first-character-of-line (atom-text-editor.editor.is-focused.autocomplete-active)
     -1:28.2.0 editor:move-to-end-of-screen-line (atom-text-editor.editor.is-focused)
     -1:26.8.0 core:move-down (atom-text-editor.editor.is-focused)
     -1:26.4.0 editor:move-to-first-character-of-line (atom-text-editor.editor.is-focused)
     -1:26.2.0 markdown-writer:insert-new-line (atom-text-editor.editor.is-focused)
     -1:26.2.0 markdown-lists:insert-new-line (atom-text-editor.editor.is-focused)
     -1:24.8.0 editor:move-to-end-of-screen-line (atom-text-editor.editor.is-focused)
     -1:24.1.0 core:move-down (atom-text-editor.editor.is-focused)
     -1:23.7.0 editor:move-to-first-character-of-line (atom-text-editor.editor.is-focused)
     -1:22.7.0 editor:move-to-end-of-screen-line (atom-text-editor.editor.is-focused)
     -1:21.9.0 core:move-up (atom-text-editor.editor.is-focused)
     -1:20.7.0 core:save (atom-text-editor.editor.is-focused)
  2x -0:08.9.0 clean2:toggle (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "vim-mode",
      "tidy-markdown",
      "markdown-pdf",
      "Zen",
      "minimap-cursorline",
      "minimap-highlight-selected",
      "minimap-pigments",
      "markdown-toc",
      "markdown-scroll-sync",
      "minimap",
      "emmet",
      "typewriter",
      "angularjs",
      "atom-beautify",
      "linter",
      "language-pfm"
    ],
    "followSymlinks": true,
    "themes": [
      "dark-flat-ui",
      "atom-zeus-syntax"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
Clean2, v0.16.0
atom-zeus-syntax, v1.0.3
auto-detect-indentation, v0.4.2
autoclose-html, v0.21.0
build-markdown, v1.0.2
color-picker, v2.1.1
dark-flat-ui, v1.2.4
file-icons, v1.6.14
highlight-selected, v0.11.2
markdown-format, v2.5.1
markdown-lists, v0.0.2
markdown-writer, v2.3.1
open-in-browsers, v0.0.11
open-recent, v5.0.0
pigments, v0.24.1

# Dev
No dev packages
```

**Comment by spacerockzero** [comment]
I'm still getting this issue. Is there a solution?

**Comment by ghost** [comment]
I'm seeing this as well.

**Comment by Cr4ck3rs** [comment]
bump

**Comment by ajtb** [comment]
another bump
