### ISSUE TITLE
Failed to activate the Clean2 package

### ISSUE THREAD

**Issue by olegshilov** [camel-chased/clean2#3]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 0.208.0
**System**: Mac OS X 10.10.3
**Thrown From**: [Clean2](https://github.com/camel-chased/clean2) package, v0.12.3
### Stack Trace

Failed to activate the Clean2 package

```
At Cannot read property 'command' of undefined

TypeError: Cannot read property 'command' of undefined
  at Object.module.exports.activate (/Users/olegshilov/.atom/packages/Clean2/lib/clean.coffee:82:23)
  at Package.module.exports.Package.activateNow (/Users/olegshilov/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:238:19)
  at /Users/olegshilov/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:770:25
  at Emitter.module.exports.Emitter.emit (/Users/olegshilov/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Users/olegshilov/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:219:20)
  at CommandRegistry.handleCommandEvent (/Users/olegshilov/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61)
  at CommandRegistry.module.exports.CommandRegistry.dispatch (/Users/olegshilov/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:153:19)
  at EventEmitter.<anonymous> (/Users/olegshilov/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:70:30)
  at emitOne (events.js:77:13)
  at EventEmitter.emit (events.js:166:7)

```
### Commands

```
     -9:07.6.0 emmet:insert-formatted-line-break-only (atom-text-editor.editor.is-focused)
     -9:07.6.0 editor:newline (atom-text-editor.editor.is-focused)
     -9:07.4.0 core:paste (atom-text-editor.editor.is-focused)
     -9:01.6.0 core:move-right (atom-text-editor.editor.is-focused)
     -9:00.9.0 editor:delete-to-beginning-of-line (atom-text-editor.editor.is-focused)
     -9:00.5.0 core:backspace (atom-text-editor.editor.is-focused)
     -8:42.6.0 core:paste (atom-text-editor#editor.fontFamily.editor.mini.is-focused)
     -8:39.6.0 editor:select-to-first-character-of-line (atom-text-editor#editor.fontFamily.editor.mini.is-focused)
     -8:37.8.0 core:backspace (atom-text-editor#editor.fontFamily.editor.mini.is-focused)
  3x -8:33.4.0 core:undo (ul.list-inline.tab-bar.inset-panel)
     -7:21 core:paste (atom-text-editor#editor.fontFamily.editor.mini.is-focused)
     -5:58.9.0 core:select-all (atom-text-editor#editor.fontFamily.editor.mini.is-focused)
     -5:58.5.0 core:paste (atom-text-editor#editor.fontFamily.editor.mini.is-focused)
  2x -0:47.4.0 core:save (atom-text-editor#editor.fontFamily.editor.mini.is-focused)
     -0:01.5.0 clean2:toggle (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {},
  "Clean2": {}
}
```
### Installed Packages

``` coffee
# User
Clean2, v0.12.3
atom-beautify, v0.28.2
color-picker, v2.0.4
emmet, v2.3.10
file-icons, v1.5.7
language-javascript-jsx, v0.3.6
linter, v0.12.7
linter-coffeelint, v0.3.2
linter-csslint, v0.0.13
linter-eslint, v0.5.8
minimap, v4.9.4
minimap-git-diff, v4.1.3
minimap-pigments, v0.1.1
pigments, v0.4.5
terminal-status, v1.6.8

# Dev
No dev packages
```

**Comment by duub** [comment]
Same problem with:

Atom Version: 0.209.0
System: Debian Jessie
Thrown From: Clean2 package, v0.14.0

**Comment by ProLoser** [comment]
Same problem with Atom Version: 1.0

**Comment by prometheas** [comment]
+1 on Atom 1.0.5

**Comment by spiritloveroot** [comment]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.0.19
**System**: Mac OS X 10.11
**Thrown From**: [Clean2](https://github.com/camel-chased/clean2) package, v0.14.0

### Stack Trace

Failed to activate the Clean2 package

```
At Cannot read property 'command' of undefined

TypeError: Cannot read property 'command' of undefined
  at Object.module.exports.activate (/Users/spirit/.atom/packages/Clean2/lib/clean.coffee:82:23)
  at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:245:19)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:838:25
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:226:20)
  at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61)
  at CommandRegistry.module.exports.CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:145:19)
  at EventEmitter.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:70:30)
  at emitOne (events.js:77:13)
  at EventEmitter.emit (events.js:169:7)

```

### Commands

```
  4x -9:46.7.0 core:close (atom-text-editor.editor.is-focused)
     -9:24.9.0 core:backspace (atom-text-editor.editor.is-focused)
  2x -9:19.9.0 editor:newline (atom-text-editor.editor.is-focused)
     -8:38.2.0 application:minimize (atom-text-editor.editor.is-focused)
     -8:37.5.0 settings-view:open (atom-text-editor.editor.is-focused)
 16x -8:29.9.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -6:13.4.0 core:confirm (atom-text-editor.editor.mini.is-focused)
  6x -1:42.7.0 zen:toggle (atom-text-editor.editor.is-focused)
     -1:19.7.0 editor:newline (atom-text-editor.editor.is-focused)
     -1:19.2.0 core:backspace (atom-text-editor.editor.is-focused)
     -1:02.1.0 settings-view:open (atom-text-editor.editor.is-focused)
     -0:36.2.0 core:close (div.settings-view.pane-item)
  8x -0:27.3.0 tree-view:toggle (atom-text-editor.editor.is-focused)
     -0:00.7.0 clean2:toggle (atom-text-editor.editor.is-focused)
```

### Config

``` json
{
  "core": {
    "openEmptyEditorOnStart": false,
    "themes": [
      "nucleus-dark-ui",
      "solarized-dark-syntax"
    ],
    "disabledPackages": [
      "Zen"
    ]
  }
}
```

### Installed Packages

``` coffee
# User
Clean2, v0.14.0
Fusion, v0.0.113
nucleus-dark-ui, v0.5.13
saveallthetime, v0.2.1

# Dev
No dev packages
```

**Comment by ktec** [comment]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.1.0
**System**: Mac OS X 10.10.4
**Thrown From**: [Clean2](https://github.com/camel-chased/clean2) package, v0.16.0

### Stack Trace

Failed to activate the Clean2 package

```
At Cannot set property 'opacity' of undefined

TypeError: Cannot set property 'opacity' of undefined
  at Object.module.exports.restoreOpacity (/Users/globalkeith/.atom/packages/Clean2/lib/clean.coffee:59:22)
  at Object.module.exports.applyConfig (/Users/globalkeith/.atom/packages/Clean2/lib/clean.coffee:84:10)
  at /Users/globalkeith/.atom/packages/Clean2/lib/clean.coffee:92:58
  at Config.module.exports.Config.observeKeyPath (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:549:7)
  at Config.module.exports.Config.observe (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:129:21)
  at Object.module.exports.activate (/Users/globalkeith/.atom/packages/Clean2/lib/clean.coffee:92:17)
  at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:232:19)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:802:25
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:86:11)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:224:20)
  at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61)
  at CommandRegistry.module.exports.CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:143:19)
  at EventEmitter.module.exports.WindowEventHandler.handleIPCCommand (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:213:28)
  at emitOne (events.js:77:13)
  at EventEmitter.emit (events.js:169:7)

```

### Commands

```
 67x -0:36.8.0 core:move-right (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
  2x -0:34.9.0 core:move-up (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
 83x -0:34.1.0 core:move-right (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
  3x -0:32.3.0 core:move-left (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
 12x -0:30.8.0 core:move-right (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
  2x -0:29.2.0 core:select-up (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
     -0:28 core:select-left (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
  2x -0:27.5.0 core:select-up (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
     -0:25.7.0 core:backspace (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
  6x -0:24.3.0 core:select-right (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
     -0:23 core:backspace (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
     -0:22.4.0 core:move-right (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
     -0:21.8.0 core:backspace (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
     -0:16.9.0 core:save (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
     -0:10.9.0 editor:toggle-soft-wrap (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
     -0:02.0 clean2:toggle (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
```

### Config

``` json
{
  "core": {
    "disabledPackages": [
      "atom-lint",
      "autocomplete-ruby",
      "motepair",
      "autocomplete-elixir",
      "elixir-cmd"
    ],
    "ignoredNames": [
      "priv"
    ]
  }
}
```

### Installed Packages

``` coffee
# User
Clean2, v0.16.0
atom-pair, v1.1.6
jshint, v1.8.3
language-arduino, v0.3.1
language-crystal-actual, v0.28.0
language-elixir, v0.5.1
language-gherkin, v1.0.2
language-javascript-jsx, v0.3.7
language-nginx, v0.5.4
leanpub-snippets, v0.2.0
linter-crystal, v3.0.0
linter-rubocop, v0.4.4
vim-mode, v0.57.0
wrap, v0.1.0

# Dev
No dev packages
```

**Comment by camel-chased** [comment]
hmmm, i really don't have time now to fix this, maybe it is easy maybe not
i don't have time even to look at it 
i don't know when i will have some, but i know about this bugs

**Comment by ProLoser** [comment]
Since Zen is still active, perhaps we should see if that project might be willing to add some features that clean / clean2 has introduced instead? Although I don't know what the different features are between the packages.
